### ISSUE TITLE
Tests???

### ISSUE THREAD

**Issue by rmarku** [rjbordon/techo_encuestas#13]
What do you think about making utest, behavior test, and testing in general?? We can use TravisCI or CodeShip as Continuous Integration. 
I know protractor for AngularJS e2e testing, it can be run on SauceLabs (limited number of runs) or locally by us and run under PhantomJS in the CI server.
Some thing for uTest? Mocha? I know nothing about Sails.JS testing, I would have to read.

**Comment by rjbordon** [comment]
sure thing, at least we need some serious unit tests, I'd like using sinonjs / chaijs (BDD style). and will go with TravisCI if possible to run protractor with phantom... no idea about sailsjs ^_^

**Comment by rmarku** [comment]
I have really little experience with testing, so if you say sinonjs/chaijs I aprove :smiley: . I have only used a little of protractor for e2e testing. Running it with Phantom.JS is not as real as with chrome or firefox, but its an option for travis. We can run firefox and chrome test in our machines...
I have research a little of Sails.JS testing. There are some answers in StackOverflow and a repo on github as an [example](https://github.com/albertosouza/sails-test-example)

**Comment by juanchosaravia** [comment]
"Thaaaaaaaaaaat oneeeeee!!!"
Eeeeessaaaaaaaaaaaaaaa!! in english
