### ISSUE TITLE
Autentificacion de usuarios

### ISSUE THREAD

**Issue by rmarku** [rjbordon/techo_encuestas#8]
Es requerido que los usuarios inicien cesión para poder utilizar el sistema.

**Comment by dariosus-techo** [comment]
Exactamente. Sería bueno que los usuarios esten asociados a un barrio para solamente ver los pines de su barrio.

Esto que digo esta muy atado a https://github.com/rjbordon/techo_encuestas/issues/3 y a https://github.com/rjbordon/techo_encuestas/issues/4

El ABM de usuarios podría ser una tarea paralela también

**Comment by rmarku** [comment]
sip, la idea era desglosar un poco lo que hacia falta par #3  y #4 , como que si o si va a hacer falta un sistema de autentificación.

Habría que definir como se manejaría. Cualquiera crea cuenta y un admin las habilita? los Admins solamente habilitan? como convendría que sea?
Por el momento hice algo en la rama [feature/autentifiacion](/rjbordon/techo_encuestas/tree/feature/autentificacion) pero todavía no esta la parte de crear los usuarios, que es lo que habría que definir.

**Comment by dariosus-techo** [comment]
Debería pensarlo mejor/charlar con los "clientes". De todas formas, creo que en una primera versión bastaria con que un usuario admin cree las cuentas.

Si prefieren esperar a que hable con las partes involucradas y apuntar a una mejor solución, diganme y apuntamos a eso

**Comment by rmarku** [comment]
Creo que para empezar puede ser el echo de que el admin cree las cuentas. Despues del 31/7 me puedo poner....

**Comment by dariosus-techo** [comment]
Genial! Yo me estaría recibiendo en 3 semanas, con lo cual mi cabeza esta un poco ahora en eso :(
